INSERT INTO omnichannel_user.`customer_orders_reservations_actions` VALUES ('c4nonfood','Submitted','PREVIO_PREPARACION','ALTA',now(),'oms_configuration',now(),'oms_configuration');
INSERT INTO omnichannel_user.`customer_orders_reservations_actions` VALUES ('c4nonfood','Incomplete','NO_RESERVA','BAJA',now(),'oms_configuration',now(),'oms_configuration');
INSERT INTO omnichannel_user.`customer_orders_reservations_actions` VALUES ('c4nonfood','splitted','PREVIO_PREPARACION','ALTA',now(),'oms_configuration',now(),'oms_configuration');
INSERT INTO omnichannel_user.`customer_orders_reservations_actions` VALUES ('c4nonfood','no_pending_action','PREVIO_PREPARACION','ALTA',now(),'oms_configuration',now(),'oms_configuration');
INSERT INTO omnichannel_user.`customer_orders_reservations_actions` VALUES ('c4nonfood','Removed','NO_RESERVA','BAJA',now(),'oms_configuration',now(),'oms_configuration');
INSERT INTO omnichannel_user.`customer_orders_reservations_actions` VALUES ('c4nonfood','pending_remove','NO_RESERVA','BAJA',now(),'oms_configuration',now(),'oms_configuration');
INSERT INTO omnichannel_user.`customer_orders_reservations_actions` VALUES ('c4nonfood','sent_to_backoffice','PREVIO_PREPARACION','ALTA',now(),'oms_configuration',now(),'oms_configuration');
INSERT INTO omnichannel_user.`customer_orders_reservations_actions` VALUES ('c4nonfood','sent_to_logistic','PREVIO_PREPARACION','ALTA',now(),'oms_configuration',now(),'oms_configuration');
INSERT INTO omnichannel_user.`customer_orders_reservations_actions` VALUES ('c4nonfood','preparing','PREPARADO','BAJA',now(),'oms_configuration',now(),'oms_configuration');
INSERT INTO omnichannel_user.`customer_orders_reservations_actions` VALUES ('c4nonfood','pending_merchant_action','PREPARADO','BAJA',now(),'oms_configuration',now(),'oms_configuration');
INSERT INTO omnichannel_user.`customer_orders_reservations_actions` VALUES ('c4nonfood','pending_customer_return','PREPARADO','BAJA',now(),'oms_configuration',now(),'oms_configuration');
INSERT INTO omnichannel_user.`customer_orders_reservations_actions` VALUES ('c4nonfood','pending_approval','PREPARADO','BAJA',now(),'oms_configuration',now(),'oms_configuration');
INSERT INTO omnichannel_user.`customer_orders_reservations_actions` VALUES ('basicSite','Creación','PREVIO_PREPARACION','ALTA',now(),'oms_configuration',now(),'oms_configuration');
INSERT INTO omnichannel_user.`customer_orders_reservations_actions` VALUES ('basicSite','Anulado en Creación','PREVIO_PREPARACION','BAJA',now(),'oms_configuration',now(),'oms_configuration');
INSERT INTO omnichannel_user.`customer_orders_reservations_actions` VALUES ('basicSite','Anulado en Creación Cliente','PREVIO_PREPARACION','BAJA',now(),'oms_configuration',now(),'oms_configuration');
INSERT INTO omnichannel_user.`customer_orders_reservations_actions` VALUES ('basicSite','Enviado a Logística','PREVIO_PREPARACION','BAJA',now(),'oms_configuration',now(),'oms_configuration');
INSERT INTO omnichannel_user.`customer_orders_reservations_actions` VALUES ('basicSite','Anulado en Enviado Logística','PREVIO_PREPARACION','BAJA',now(),'oms_configuration',now(),'oms_configuration');
INSERT INTO omnichannel_user.`customer_orders_reservations_actions` VALUES ('basicSite','Anulado en Enviado Logística Cliente','PREVIO_PREPARACION','BAJA',now(),'oms_configuration',now(),'oms_configuration');
INSERT INTO omnichannel_user.`customer_orders_reservations_actions` VALUES ('basicSite','Expedido','PREPARADO','BAJA',now(),'oms_configuration',now(),'oms_configuration');
INSERT INTO omnichannel_user.`customer_orders_reservations_actions` VALUES ('basicSite','Anulado en fecha entrega','PREVIO_PREPARACION','BAJA',now(),'oms_configuration',now(),'oms_configuration');
INSERT INTO omnichannel_user.`customer_orders_reservations_actions` VALUES ('basicSite','Anulado en Expedido','NO_RESERVA','BAJA',now(),'oms_configuration',now(),'oms_configuration');
INSERT INTO omnichannel_user.`customer_orders_reservations_actions` VALUES ('basicSite','Reembolsado','NO_RESERVA','BAJA',now(),'oms_configuration',now(),'oms_configuration');
INSERT INTO omnichannel_user.`customer_orders_reservations_actions` VALUES ('bodegaSite','Creación','PREVIO_PREPARACION','ALTA',now(),'oms_configuration',now(),'oms_configuration');
INSERT INTO omnichannel_user.`customer_orders_reservations_actions` VALUES ('bodegaSite','Anulado en Creación','PREVIO_PREPARACION','BAJA',now(),'oms_configuration',now(),'oms_configuration');
INSERT INTO omnichannel_user.`customer_orders_reservations_actions` VALUES ('bodegaSite','Anulado en Creación Cliente','PREVIO_PREPARACION','BAJA',now(),'oms_configuration',now(),'oms_configuration');
INSERT INTO omnichannel_user.`customer_orders_reservations_actions` VALUES ('bodegaSite','Enviado a Logística','PREVIO_PREPARACION','BAJA',now(),'oms_configuration',now(),'oms_configuration');
INSERT INTO omnichannel_user.`customer_orders_reservations_actions` VALUES ('bodegaSite','Anulado en Enviado Logística','PREVIO_PREPARACION','BAJA',now(),'oms_configuration',now(),'oms_configuration');
INSERT INTO omnichannel_user.`customer_orders_reservations_actions` VALUES ('bodegaSite','Anulado en Enviado Logística Cliente','PREVIO_PREPARACION','BAJA',now(),'oms_configuration',now(),'oms_configuration');
INSERT INTO omnichannel_user.`customer_orders_reservations_actions` VALUES ('bodegaSite','Expedido','PREPARADO','BAJA',now(),'oms_configuration',now(),'oms_configuration');
INSERT INTO omnichannel_user.`customer_orders_reservations_actions` VALUES ('bodegaSite','Anulado en fecha entrega','PREVIO_PREPARACION','BAJA',now(),'oms_configuration',now(),'oms_configuration');
INSERT INTO omnichannel_user.`customer_orders_reservations_actions` VALUES ('bodegaSite','Anulado en Expedido','NO_RESERVA','BAJA',now(),'oms_configuration',now(),'oms_configuration');
INSERT INTO omnichannel_user.`customer_orders_reservations_actions` VALUES ('bodegaSite','Reembolsado','NO_RESERVA','BAJA',now(),'oms_configuration',now(),'oms_configuration');